name: galaxiesbook
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipython
  - jupyter
  - numpy
  - scipy
  #- matplotlib
  - pyqt
  - pandas
  - pip
  - numexpr
  - conda-forge::astropy>=2
  - conda-forge::specutils
  - pip:
    - astroquery
    - matplotlib
    - git+https://github.com/jobovy/galpy.git@5af471eb0b7eee60629a424e01f0e28168d8e770
