name: galaxiesbook
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ipython
  - jupyter
  - numpy
  - scipy
  - matplotlib
  - pyqt
  - pandas
  - pip
  - conda-forge::astropy>=2
  - conda-forge::specutils
  - pip:
    - astroquery
    - git+https://github.com/jobovy/galpy.git@f2200a97413874030aad69d209e5de7025d93778
