name: galdyncourse
channels:
  - conda-forge
dependencies:
  - python=3.7
  - ipython
  - jupyter
  - numpy
  - scipy
  - matplotlib
  - pyqt
  - pandas
  - pip
  - pandoc=2.1.3
  - conda-forge::astropy>=2
  - conda-forge::galpy
  - pip:
    - astroquery
